In [2]:
import os
import pandas as pd

In [3]:
# enter path to CSV files
path = os.getcwd()

In [15]:
# List with all CSV files
csv_files = [path+'/'+file for file in os.listdir(path) if file.endswith('.csv')]

In [11]:
csv_data = []

In [17]:
for file in csv_files:
    csv_data.append(pd.read_csv(file))

In [19]:
csv_merged = pd.concat(csv_data, ignore_index=True)

In [20]:
csv_merged.to_csv(path+'/merged-job-details.csv',index=False)

In [22]:
df = pd.read_csv('merged-job-details.csv')

In [25]:
df.head(50)

,Job Title,Company,Location,Job Highlights,Full Job Description,Reviews,Job Type,Qualification,Experience,Salary,Posted on,Required Skills,Application Link,Search Term
0,Data Engineer: Big Data,IBM,Bangalore/Bengaluru,NaN,Be involved in data engineering activities lik...,15586.0,"Full Time, Permanent","UG :B.Tech/B.E., PG :Post Graduation Not Required",2 - 5 years,Not Disclosed,3 days ago,"Data migration, github, Version control, devop...",https://www.naukri.com/job-listings-data-engin...,data engineer
1,Senior Data Engineer,Novo Nordisk India,Bangalore/Bengaluru,NaN,Experience in AWS as Cloud Engineer/ Cloud Dev...,599.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",5 - 10 years,Not Disclosed,4 days ago,NaN,https://www.naukri.com/job-listings-senior-dat...,data engineer
2,Senior Data Engineer,Visa,Bangalore/Bengaluru,NaN,Support Data warehouse Engineering in the arch...,103.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",7 - 12 years,Not Disclosed,4 days ago,NaN,https://www.naukri.com/job-listings-senior-dat...,data engineer
3,Data Engineer: Big Data,IBM,Hyderabad/Secunderabad,"As Big Data Engineer, you will develop, mainta...","As Big Data Engineer, you will develop, mainta...",15586.0,"Full Time, Permanent","UG :B.Tech/B.E., PG :Post Graduation Not Required",7 - 12 years,Not Disclosed,3 days ago,"Interpersonal skills, GIT, Time management, Ha...",https://www.naukri.com/job-listings-data-engin...,data engineer
4,Data Engineer: Big Data,IBM,Hyderabad/Secunderabad,NaN,Your Role and Responsibilities Be involved in ...,15586.0,"Full Time, Permanent","UG :B.Tech/B.E., PG :Post Graduation Not Required",2 - 5 years,Not Disclosed,5 days ago,"Data migration, github, Version control, devop...",https://www.naukri.com/job-listings-data-engin...,data engineer
5,Data Engineer: Big Data,IBM,Gurgaon/Gurugram,NaN,"As Data Engineer, you will develop, maintain, ...",15586.0,"Full Time, Permanent","UG :B.Tech/B.E., PG :Post Graduation Not Required",4 - 8 years,Not Disclosed,5 days ago,"Interpersonal skills, Hadoop, SCALA, Programming",https://www.naukri.com/job-listings-data-engin...,data engineer
6,"Big Data engineer -Scala,Spark",Job Fittment Finder,"Hyderabad/Secunderabad, Bangalore/Bengaluru",We Urgently Looking for Big Data engineer havi...,We Urgently Looking for Big Data engineer havi...,NaN,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",4 - 9 years,Not Disclosed,2 days ago,"Java, REST, Software development, Scala, data ...",https://www.naukri.com/job-listings-big-data-e...,data engineer
7,Azure Data Engineer,Deloitte,"Kolkata, Hyderabad/Secunderabad, Pune, Chennai...",What impact will you make?,"What impact will you make? Every day, your wor...",10240.0,"Full Time, Permanent","UG :B.Tech/B.E. in Any Specialization, B.Sc in...",5 - 10 years,Not Disclosed,3 days ago,data modeling,https://www.naukri.com/job-listings-azure-data...,data engineer
8,Snowflake Developer - Data Engineer,Ecolab Digital Center (EDC),Bangalore/Bengaluru,NaN,The Data Engineer will support our software de...,30.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",2 - 5 years,Not Disclosed,2 days ago,NaN,https://www.naukri.com/job-listings-snowflake-...,data engineer
9,"Data Engineer Datapipeline Scala, Python, Spar...",Full time with top German MNC,Bangalore/Bengaluru,Full time with top German MNC for location Ban...,Full time with top German MNC for location Ban...,NaN,"Full Time, Permanent","UG :B.Tech/B.E. in Any Specialization, PG :MCA...",3 - 6 years,Not Disclosed,1 day ago,NaN,https://www.naukri.com/job-listings-data-engin...,data engineer
10,SDE II - Data Engineer,Glance,Bangalore/Bengaluru,NaN,Responsible for solving high complexity issu...,11.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",3 - 5 years,Not Disclosed,2 days ago,NaN,https://www.naukri.com/job-listings-sde-ii-dat...,data engineer
11,SDE II - Data Engineer,roposo,Bangalore/Bengaluru,NaN,Responsible for solving high complexity issu...,14.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",3 - 5 years,Not Disclosed,2 days ago,NaN,https://www.naukri.com/job-listings-sde-ii-dat...,data engineer
12,Senior Data Engineer,Nike,Bangalore/Bengaluru,NaN,"Design and build reusable components, framewor...",122.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",8 - 10 years,Not Disclosed,5 days ago,NaN,https://www.naukri.com/job-listings-senior-dat...,data engineer
13,"Senior Data Engineer,Data Engineering",Lennox India Technology Centre Private Limited,"Hyderabad/Secunderabad, Bangalore/Bengaluru",NaN,The primary objective of Data Engineering spec...,59.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",8 - 10 years,Not Disclosed,4 days ago,NaN,https://www.naukri.com/job-listings-senior-dat...,data engineer
14,Sr. Data engineer,Job Fittment Finder,"Hyderabad/Secunderabad, Bangalore/Bengaluru",NaN,"Must Have Skills : Python,pySpark Key Respons...",NaN,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",4 - 9 years,Not Disclosed,3 days ago,"Pyspark, Hive, Azure, EC2, Frame Work, SQL Ser...",https://www.naukri.com/job-listings-sr-data-en...,data engineer
15,Data Engineer,IBM,Bangalore/Bengaluru,NaN,Data Manager/Engineer is responsible for updat...,15586.0,"Full Time, Permanent","UG :B.Tech/B.E., PG :Post Graduation Not Required",3 - 7 years,Not Disclosed,5 days ago,"RDBMS, Dms, Selenium, User acceptance testing,...",https://www.naukri.com/job-listings-data-engin...,data engineer
16,Staff Data Engineer - Analytics,Visa,Bangalore/Bengaluru,NaN,Work with Business stakeholders to understand ...,103.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",10 - 20 years,Not Disclosed,4 days ago,NaN,https://www.naukri.com/job-listings-staff-data...,data engineer
17,Data Engineer,Globallogic,Bangalore/Bengaluru,Job Description: Data Engineer\n\nExperience\n...,Job Description: Data Engineer Experience • 5...,2206.0,"Full Time, Permanent","UG :B.Tech/B.E. in Any Specialization, PG :MS/...",3 - 7 years,Not Disclosed,4 days ago,"Hive, Azure, java, etl, data engineering",https://www.naukri.com/job-listings-data-engin...,data engineer
18,Data Engineer: Data Warehouse,IBM,Bangalore/Bengaluru,NaN,"As Snowflake Developer, you are responsible to...",15586.0,"Full Time, Permanent","UG :B.Tech/B.E., PG :Post Graduation Not Required",5 - 10 years,Not Disclosed,5 days ago,"Data migration, NoSQL, Debugging, Stored proce...",https://www.naukri.com/job-listings-data-engin...,data engineer
19,Data Engineer: Data Integration,IBM,Mumbai,NaN,"As Data engineer, you will develop and move da...",15586.0,"Full Time, Permanent","UG :B.Tech/B.E., PG :Post Graduation Not Required",6 - 10 years,Not Disclosed,5 days ago,"data cleansing, Interpersonal skills, Time man...",https://www.naukri.com/job-listings-data-engin...,data engineer
20,Azure Data Engineer || Infogain,Infogain,"Noida, Mumbai, Pune, Bangalore/Bengaluru",Data Engineer,Data Engineer 6+ Years experience in Azure St...,620.0,"Full Time, Permanent","UG :B.Tech/B.E. in Any Specialization, PG :MCA...",6 - 11 years,Not Disclosed,4 days ago,"Synapse, Dremio, Ms Sql Server Dba, ADLS",https://www.naukri.com/job-listings-azure-data...,data engineer
21,Azure Data Engineer,Xoriant,"Kochi/Cochin, Hyderabad/Secunderabad, Pune, Gu...",Roles and Responsibilities :,Roles and Responsibilities : Key Skills Azure ...,973.0,"Full Time, Permanent",UG :Any Graduate,7 - 12 years,Not Disclosed,3 days ago,"Azure Data Lake, ssis",https://www.naukri.com/job-listings-azure-data...,data engineer
22,Data Engineer,Brillio,Bangalore/Bengaluru,,The Big Data Analytics Engineer will help de...,414.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",6 - 10 years,Not Disclosed,3 days ago,NaN,https://www.naukri.com/job-listings-data-engin...,data engineer
23,Data Engineer,Rapido,Bangalore/Bengaluru,NaN,Role and Responsibilities: Creating complex da...,160.0,"Full Time, Permanent","UG :B.Tech/B.E. in Computers, PG :M.Tech in Co...",2 - 4 years,Not Disclosed,3 days ago,"python, open source, data engineers, tdd, Data...",https://www.naukri.com/job-listings-data-engin...,data engineer
24,Azure ETL Data Engineer,CGI,Bangalore/Bengaluru,Design and develop ETL processes based on func...,Design and develop ETL processes based on func...,2023.0,"Full Time, Permanent","UG :B.Tech/B.E., PG :M.Tech",2 - 6 years,Not Disclosed,3 days ago,"CGI, JSON, JIRA, Release management",https://www.naukri.com/job-listings-azure-etl-...,data engineer
25,Data Engineer,CGI,Bangalore/Bengaluru,NaN,The current role is within a team that has bee...,2023.0,"Full Time, Permanent","UG :B.Tech/B.E., PG :Any Postgraduate",2 - 5 years,Not Disclosed,5 days ago,"Business consulting, CGI, Software development...",https://www.naukri.com/job-listings-data-engin...,data engineer
26,Senior Data Engineer,Third Eye Data Analytics Services India Privat...,"Kolkata, Hubli, Bangalore/Bengaluru",ThirdEye Data is looking to hire Data Engineer...,ThirdEye Data is looking to hire Data Engineer...,6.0,"Full Time, Permanent","UG :B.Tech/B.E. in Any Specialization, BCA in ...",5 - 7 years,"₹ 12,00,000 - 16,00,000 P.A.",3 days ago,"hive, Java, GCP, Machine Learning, AWS, hbase,...",https://www.naukri.com/job-listings-senior-dat...,data engineer
27,Exciting opportunity For Data Engineer and Sr ...,EXL,"Gurgaon/Gurugram, Bangalore/Bengaluru",NaN,Job Location: Gurgaon (India)/Bangalore Experi...,983.0,"Full Time, Permanent",UG :Any Graduate,4 - 9 years,Not Disclosed,12 days ago,"Hadoop, Big Data, numpy, Spark, SQL",https://www.naukri.com/job-listings-exciting-o...,data engineer
28,Sr. Data Engineer,Accolite Software India Pvt Ltd,"Hyderabad/Secunderabad, Bangalore/Bengaluru",NaN,Liaising with coworkers and clients to elucida...,310.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",6 - 8 years,Not Disclosed,13 days ago,NaN,https://www.naukri.com/job-listings-sr-data-en...,data engineer
29,Senior Data Engineer,Superior Group,Bangalore/Bengaluru,NaN,Translates complex cross-functional business r...,14.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",3 - 7 years,Not Disclosed,4 days ago,NaN,https://www.naukri.com/job-listings-senior-dat...,data engineer
30,Senior Associate - Data Engineer - D&AT IFS,PwC,Bangalore/Bengaluru,NaN,Execution of daily batch processing of data vi...,4090.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",2 - 7 years,Not Disclosed,13 days ago,NaN,https://www.naukri.com/job-listings-senior-ass...,data engineer
31,"Sr Data Engineer ,SAP BO - EDW",Pearson,Bangalore/Bengaluru,NaN,Position Summary The Data Engineer is part of ...,57.0,"Full Time, Permanent","UG :B.Sc in Computers, BCA in Computers, B.Tec...",3 - 6 years,Not Disclosed,14 days ago,"SAP BO, python, java, Bigquery, ETL",https://www.naukri.com/job-listings-sr-data-en...,data engineer
32,Senior Data Engineer | Hy-Vee,Talent500,Bangalore/Bengaluru,NaN,Primary Duties and Responsibilities Experienc...,13.0,"Full Time, Permanent",UG :Any Graduate,6 - 11 years,Not Disclosed,5 days ago,NaN,https://www.naukri.com/job-listings-senior-dat...,data engineer
33,Senior Consultant Data Engineer,Visa,Bangalore/Bengaluru,NaN,As a Senior Consultant Data Engineer you will ...,103.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",6 - 11 years,Not Disclosed,11 days ago,NaN,https://www.naukri.com/job-listings-senior-con...,data engineer
34,Data Engineer - ED&A,Nike,Bangalore/Bengaluru,NaN,Design and build simple (non - complex) reusab...,122.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",0 - 4 years,Not Disclosed,3 days ago,NaN,https://www.naukri.com/job-listings-data-engin...,data engineer
35,"Data Engineer(Python, Spark, Hive/ SQL )",Asky Services Llp,Pune,Must Have:\n\n• Tech savvy engineer - willing ...,Must Have: • Tech savvy engineer - willing an...,NaN,"Full Time, Permanent",UG :B.Tech/B.E. in Any Specialization,3 - 5 years,"₹ 15,00,000 - 25,00,000 P.A.",3 days ago,hadoop,https://www.naukri.com/job-listings-data-engin...,data engineer
36,Azure Data Engineer,Wavicle Data Solutions,"Chennai, Coimbatore",NaN,Strong hands-on experience implementing big-da...,24.0,"Full Time, Permanent",UG :Any Graduate,2 - 7 years,Not Disclosed,3 days ago,NaN,https://www.naukri.com/job-listings-azure-data...,data engineer
37,Azure Data Engineer,Audax Labs,Noida,NaN,Experience with Azure Data Factory Experienc...,10.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",1 - 3 years,Not Disclosed,2 days ago,NaN,https://www.naukri.com/job-listings-azure-data...,data engineer
38,Data Engineer,Syren Technologies,Hyderabad/Secunderabad,NaN,"Role: Data Engineer MUST SKILLS: PYTHON, PYSPA...",4.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",4 - 9 years,Not Disclosed,2 days ago,"data modeling, data profiling",https://www.naukri.com/job-listings-data-engin...,data engineer
39,Azure Data Engineer,Mdtechnosoft,Hiring office located in Hyderabad/Secunderabad,NaN,Remote / Freelance Job- Azure Data Engineer H...,NaN,"Part Time, Freelance/Homebased",UG :B.A in Any Specialization,8 - 13 years,Not Disclosed,1 day ago,lake,https://www.naukri.com/job-listings-azure-data...,data engineer
40,Data Engineer,Programmers io,Hiring office located in Jaipur,Roles and Responsibilities,Roles and Responsibilities Build data pipelin...,88.0,"Full Time, Permanent",UG :Any Graduate,4 - 9 years,"₹ 16,00,000 - 30,00,000 P.A.",2 days ago,"SQL Database, Data Bricks",https://www.naukri.com/job-listings-data-engin...,data engineer
41,Lead Data Engineer - ED&A,Nike,Bangalore/Bengaluru,NaN,"Design and build reusable components, framewor...",122.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",8 - 10 years,Not Disclosed,5 days ago,NaN,https://www.naukri.com/job-listings-lead-data-...,data engineer
42,Data Engineer: Big Data,IBM,Gurgaon/Gurugram,NaN,Your Role and Responsibilities Be involved in ...,15586.0,"Full Time, Permanent","UG :B.Tech/B.E., PG :Post Graduation Not Required",2 - 5 years,Not Disclosed,14 days ago,"Data migration, github, Version control, devop...",https://www.naukri.com/job-listings-data-engin...,data engineer
43,Senior Associate Data Engineer,Themathcompany,Hiring office located in Bangalore/Bengaluru,WHATS IN IT FOR YOU:,WHATS IN IT FOR YOU: An exciting opportunity t...,82.0,"Full Time, Permanent",UG :B.Tech/B.E. in Any Specialization,4 - 6 years,Not Disclosed,10 days ago,"Data Anlalytics, Pyspark, Azure Data Factory, ...",https://www.naukri.com/job-listings-senior-ass...,data engineer
44,Senior Consultant - Data Engineer,"ThoughtWorks, Inc.",Bangalore/Bengaluru,NaN,Bringing the business and technology together ...,NaN,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",5 - 10 years,Not Disclosed,13 days ago,NaN,https://www.naukri.com/job-listings-senior-con...,data engineer
45,AWS Data Engineer,Capgemini,"Kolkata, Hyderabad/Secunderabad, Pune, Chennai",Job Description,Job Description Collaborate with business user...,23850.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",9 - 12 years,Not Disclosed,3 days ago,"S3, data warehouse, PySpark, Hadoop, Big Data,...",https://www.naukri.com/job-listings-aws-data-e...,data engineer
46,AWS Data Engineer,Capgemini,"Kolkata, Hyderabad/Secunderabad, Pune, Chennai",Job Description,Job Description * Implementing ETL pipelines w...,23850.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",6 - 11 years,Not Disclosed,3 days ago,"Unix, Business Intelligence, Snow SQL, PySpark...",https://www.naukri.com/job-listings-aws-data-e...,data engineer
47,"AWS Data Engineer ( Python, SQL and Airflow )",Coforge,"Bangalore/Bengaluru, Greater Noida","Dear Candidate,","Dear Candidate, We are Hiring For AWS Data En...",991.0,"Full Time, Permanent",UG :Any Graduate,5 - 9 years,Not Disclosed,3 days ago,"python, airflow, sql",https://www.naukri.com/job-listings-aws-data-e...,data engineer
48,Data Engineer,Allstate Solutions (ASPL),Bangalore/Bengaluru,NaN,Looking for DataEngineer resource having 4 to ...,773.0,"Full Time, Permanent","UG :Any Graduate, PG :Any Postgraduate",4 - 6 years,Not Disclosed,4 days ago,"S3, python, Scala, Java coding, Kafka, Kinesis...",https://www.naukri.com/job-listings-data-engin...,data engineer
49,Data Engineer: Data Warehouse,IBM,Hyderabad/Secunderabad,"As Data Warehouse Engineer, you are responsibl...","As Data Warehouse Engineer, you are responsibl...",15586.0,"Full Time, Permanent","UG :B.Tech/B.E., PG :Post Graduation Not Required",2 - 5 years,Not Disclosed,3 days ago,"Data migration, Interpersonal skills, Time man...",https://www.naukri.com/job-listings-data-engin...,data engineer